apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-deployment
  labels:
    app: health-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: health-app
  template:
    metadata:
      labels:
        app: health-app
    spec:
      containers:
      - name: healthcare-container
        image: deepikaarjunan/healthcare-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-service
  labels:
    app: health-app
spec:
  selector:
    app: health-app

  type: NodePort
  ports:
  - nodePort: 32700
    port: 8082
    targetPort: 8082
